
```{r}
## NOW LOOK AT INHIBITORY NEURONS VENTRICULAR ZONE DATA
```


```{r cars}
library(Seurat) 
#library(SeuratDisk)
#library(SeuratData)
library(ggplot2)
library(patchwork)
library(dplyr)
#library(sceasy)
library(reticulate)
#library(rliger)
library(magrittr) # needs to be run every time you start R and want to use %>%
library(dplyr) 
library(Seurat)
library(tidyverse)
library(SeuratWrappers)
library(harmony)
library(batchelor)
library(usethis)
library(Seurat)
library(monocle3)
library(dplyr)
```


```{r}
URL <- readRDS("URL.rds")
```



```{r}
URL_dcn <- subset(URL, subset = cell_type %in% c("Int+LatProg", "Int+LatDCN", "DCNProgX", "MedProg", "MedDCN"))

```


```{r}
URL_dcn.mnn <- RunFastMNN(object.list = SplitObject(URL_dcn, split.by = "Sample"), assay = "SCT", features =10000, verbose = FALSE)
URL_dcn[["mnn"]] <- CreateDimReducObject(Embeddings(URL_dcn.mnn, reduction = "mnn"), assay = "SCT")

```

```{r}
URL_dcn <- RunUMAP(URL_dcn, reduction = "mnn", dims = 1:50, return.model = T)
```


```{r}
DimPlot(URL_dcn, reduction = "umap", group.by = 'TimePoint', pt.size = 1)
DimPlot(URL_dcn, reduction = "umap", group.by = 'orig.ident', pt.size = 1)
DimPlot(URL_dcn, reduction = "umap", group.by = 'cell_type', pt.size = 1)

FeaturePlot(URL_dcn, features = c( "Zfhx3"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Olig2"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Lmx1a"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Tbr1"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Eomes"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Lhx9"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Ntng1"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Olig2"), pt.size = , max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Robo3"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Pax6"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Prox1"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Ntng1"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn, features = c( "Pax5"), pt.size = 1, max.cutoff = 3)


```
```{r}
DimPlot(URL_dcn, reduction = "umap", group.by = 'fine_cell_type', pt.size = 1, label = TRUE)

```

```{r}
URL_dcn <- FindNeighbors(URL_dcn)
URL_dcn <- FindClusters(URL_dcn, resolution = 2)

```

```{r}
DimPlot(URL_dcn, label =TRUE)
```
```{r}
#Remove Zfhx3 and Pax5+ cells
URL_dcn_subset <- subset(URL_dcn, !(RNA_snn_res.2 %in% c(3,7,14)))

```

```{r}
URL_dcn_subset.mnn <- RunFastMNN(object.list = SplitObject(URL_dcn_subset, split.by = "Sample"), features = 1000, assay = "RNA", verbose = FALSE)
URL_dcn_subset[["mnn"]] <- CreateDimReducObject(Embeddings(URL_dcn_subset.mnn, reduction = "mnn"), assay = "RNA")

```

```{r}
URL_dcn_subset <- RunUMAP(URL_dcn_subset, reduction = "mnn", dims = 1:30, return.model = T)
```

```{r}
DimPlot(URL_dcn_subset, reduction = "umap",pt.size = 1)
DimPlot(URL_dcn_subset, reduction = "umap", group.by = 'orig.ident', pt.size = 1)
DimPlot(URL_dcn_subset, reduction = "umap", group.by = 'fine_cell_type', pt.size = 1)

FeaturePlot(URL_dcn_subset, features = c( "Xist"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Olig2"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Lmx1a"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Tbr1"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Eomes"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Lhx9"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Ntng1"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Olig2"), pt.size = , max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Robo3"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Irx3"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Pax6"), pt.size = 1, max.cutoff = 3)
FeaturePlot(URL_dcn_subset, features = c( "Prox1"), pt.size = 1, max.cutoff = 3)

#@FeaturePlot(CN_all_, features = c( ""))

```

```{r}
URL_dcn_subset <- FindNeighbors(URL_dcn_subset)
URL_dcn_subset <- FindClusters(URL_dcn_subset, resolution = 2)

```

```{r}
DimPlot(URL_dcn_subset, label =TRUE)
```



```{r}
#Remove Zfhx3 and Pax5+ cells fated for outside cerebellum

URL_dcn_subset_ref <- subset(URL_dcn_subset, !(RNA_snn_res.2 %in% c(7,23,19)))
URL_dcn_subset_ref <- subset(URL_dcn_subset_ref, Zfhx3 <1)
URL_dcn_subset_ref <- subset(URL_dcn_subset_ref, Pax5 <1)

```

```{r}
URL_dcn_subset_ref.mnn <- RunFastMNN(object.list = SplitObject(URL_dcn_subset_ref, split.by = "Sample"), features = 1000, assay = "RNA", verbose = FALSE)
URL_dcn_subset_ref[["mnn"]] <- CreateDimReducObject(Embeddings(URL_dcn_subset_ref.mnn, reduction = "mnn"), assay = "RNA")

```

```{r}
URL_dcn_subset_ref <- RunUMAP(URL_dcn_subset_ref, reduction = "mnn", dims = 1:50, return.model = T)
```



```{r}
URL_dcn_subset_ref <- FindNeighbors(URL_dcn_subset_ref)
URL_dcn_subset_ref <- FindClusters(URL_dcn_subset_ref, resolution = 4)

```
```{r}
DimPlot(URL_dcn_subset_ref, label = TRUE )

```







```{r}
options(future.globals.maxSize = 8000 *1024^2)
```


```{r}
e17_keb <- readRDS("C:/Users/kebsc/OneDrive/Documents/e17cn_ke_8-2025.rds")
e17_keb$Sample <- "e17_keb"
e17_keb$TimePoint <- "E17"
e17_bl <- readRDS("C:/Users/kebsc/OneDrive/Documents/e17cn_bl.rds")
e17_bl$Sample <- "e17_bl"
e17_bl$TimePoint <- "E17"
#e17_keb <- SCTransform(e17_keb)

#e17_bl <- SCTransform(e17_bl)

```



```{r}
load("C:/Users/kebsc/Downloads/GSE160471_RAW/GSM4873765_mouse_data.RData/GSM4873765_mouse_data.RData")
```

```{r}
rm(VZ)
RL <- UpdateSeuratObject(RL)
RL$Sample <- RL$orig.ident
RL$TimePoint <- "adult"
#RL <- SCTransform(RL)

```


```{r}
DefaultAssay(e17_bl) <- "RNA"
DefaultAssay(e17_keb) <- "RNA"

# Keep the full object, but reduce the RNA assay only
e17_bl[["SCT"]] <- NULL
e17_keb[["SCT"]] <- NULL
URL_dcn_subset_ref[["RNA"]] <- subset(URL_dcn_subset_ref[["RNA"]], features = rownames(URL_dcn_subset_ref[["SCT"]]))
#RL[["RNA"]] <- subset(RL[["RNA"]], features = rownames(RL[["SCT"]]))

gene_lists <- list(
  rownames(URL_dcn_subset_ref),
  rownames(RL),
  rownames(e17_bl),
  rownames(e17_keb)
)

common.genes <- Reduce(intersect, gene_lists)
length(common.genes)


e17_bl_ <- subset(e17_bl, features = common.genes)
e17_keb_ <- subset(e17_keb, features = common.genes)
URL_ <- subset(URL_dcn_subset_ref, features = common.genes)
RL_ <- subset(RL, features = common.genes)


```
```{r}
e17 <- e17_keb#merge(e17_keb, e17_bl)
e17 <- JoinLayers(e17)
e17 <- NormalizeData(e17)
e17 <- ScaleData(e17)
```


```{r}
e17 <- FindVariableFeatures(e17)
e17 <- RunPCA(e17)
e17 <- RunUMAP(e17, dims = 1:30)
```


```{r}
e17 <- FindNeighbors(e17)

e17 <- FindClusters(e17)
DimPlot(e17, group.by = "seurat_clusters")
DimPlot(e17, group.by = "Sample")

```
```{r}
VlnPlot(e17, features = "Zfhx3")

```





```{r}
e17 <- FindClusters(e17)
DimPlot(e17)
```


```{r}
library(Seurat)
library(patchwork)
options(future.globals.maxSize = 10000 * 1024^2)

# 1) Merge your three references into one Seurat object if you like,
#    but then immediately split by sample:
combined <- merge(URL_, y = c(e17_bl_, e17_keb_, RL_), project="URL_jk")

sex_genes_mouse <- c(
  "Xist", "Tsix", "Kdm6a", "Eif2s3x", "Kdm5c", "Ddx3x", "Usp9x", "Bcor",
  "Car5b", "Smcx", "Shroom4", "Mecp2",
  "Ddx3y", "Eif2s3y", "Kdm5d", "Uty", "Usp9y",
  "Jarid1d", "Rbmy", "Zfy1", "Zfy2", "Sry", "Tspy", "Pramel1", "Tmsb4y"
)
combined <- subset(combined, features = setdiff(rownames(combined), sex_genes_mouse))



```


```{r}
# Count cells per orig.ident
cell_counts <- table(combined$Sample)

# Keep only groups with >= 2 cells
valid_idents <- names(cell_counts[cell_counts > 5])

# Subset the Seurat object
combined <- subset(combined, subset = Sample %in% valid_idents)
```





```{r}
combined <- SCTransform(combined, verbose = FALSE)
combined.mnn <- RunFastMNN(object.list = SplitObject(combined, split.by = "Sample"), assay = "SCT", verbose = FALSE)

```




```{r}
combined[["mnn"]] <- CreateDimReducObject(Embeddings(combined.mnn, reduction = "mnn"), assay = "SCT")

```

```{r}
#combined <- FindNeighbors(combined, reduction = "mnn", dims = 1:20, nn.method = "rann")
combined <- RunUMAP(combined, reduction = "mnn", dims = 1:50, nn.method = 'rann')
```


```{r}
combined <- FindNeighbors(combined, reduction = "mnn")
```


```{r}
combined <- FindClusters(combined, resolution = 2)

```

```{r}
DimPlot(combined, label =TRUE)
DimPlot(combined, group.by = "TimePoint", label =TRUE)
DimPlot(combined, group.by = "cell_type", label =TRUE)
DimPlot(combined, group.by = "subareas", label =TRUE)
```

```{r}
#remove cells (primarily from e17) that do not integrate well with this embedding space and formed a clustered ball.
combined_alltp <- subset(combined, idents =  c('20','11','21', '23', '12', '6', '13', '22', '7', '17', '25', '19', '18', '15', '26', '27', '16', '24'))
```






```{r}
# Count cells per orig.ident
cell_counts <- table(combined_alltp$Sample)

# Keep only groups with >= 2 cells
valid_idents <- names(cell_counts[cell_counts > 5])

# Subset the Seurat object
combined_alltp <- subset(combined_alltp, subset = Sample %in% valid_idents)

combined_alltp.mnn <- RunFastMNN(object.list = SplitObject(combined_alltp, split.by = "Sample"), features = 400, assay = "SCT",  verbose = FALSE)
```
```{r}
combined_alltp[["mnn"]] <- CreateDimReducObject(Embeddings(combined_alltp.mnn, reduction = "mnn"), assay = "SCT")
```

```{r}
combined_alltp <- FindNeighbors(combined_alltp, reduction = "mnn",dims = 1:50)
combined_alltp <- RunUMAP(combined_alltp, reduction = "mnn", dims = 1:50, return.model = T)
```


```{r}
DimPlot(combined_alltp, reduction = "umap", label = TRUE)
DimPlot(combined_alltp, reduction = "umap", group.by = 'subareas', size = 1)
DimPlot(combined_alltp, reduction = "umap", group.by = 'ident', size = 1)
DimPlot(combined_alltp, reduction = "umap", group.by = 'classes', size = 1)
DimPlot(combined_alltp, reduction = "umap", group.by = 'fine_cell_type', size = 1)
FeaturePlot(combined_alltp, features = "Atoh1")
```

```{r}
#combined_alltp <-FindClusters(combined_alltp, resolution =2)#default = 1.2 
DimPlot(combined_alltp, reduction = "umap", label  = TRUE)
```

```{r}
combined_alltp <- FindClusters(combined_alltp, assay = "SCT", resolution = 1.2)
```



```{r}
combined_alltp$branch <- recode(combined_alltp$SCT_snn_res.1.2,
    "0" = "Int/Lat Prog", 
    "1" = "Med",
    "2" = "IntA/Lat", 
    "3" = "RL",
    "4" = "RL", 
    "5" = "Med",
    "6" = "IntA/Lat", 
    "7" = "IntA/Lat",
    "8" = "IntP", 
    "9" = "Med",
    "10" = "IntA/Lat", 
    "11" = "Med",
    "12" = "IntP",
    "13" = "IntA/Lat", 
    "14" = "Med",
    "15" = "Med",
    "16" = "IntP", 
    "17" = "IntP",
    '18'="Med_gly"

  
    # Add more as needed
)

library(stringr)

# Remove suffix "_1" from cell names in combined_alltp
new_cells <- str_remove(Cells(combined_alltp), "_1$")  # Remove trailing "_1"

# Rename cells in combined_alltp with cleaned names
combined_alltp <- RenameCells(combined_alltp, new.names = new_cells)

# Match cell names of URL to combined_alltp
match_idx <- match(Cells(URL), Cells(combined_alltp))

# Assign branch labels from combined_alltp to URL, NA if no match
URL$branch_intlat <- ifelse(
  !is.na(match_idx),
  as.character(combined_alltp$branch[match_idx]),
  NA
)



```





```{r}

combined_alltp_noadult <- subset(combined_alltp, TimePoint != "adult") #TimePoint %in% c('E11.5', 'E12.5', 'E13.5', 'E14.5'))
# ---------------------------------------------------------
# 4. Plot UMAP with consistent colors
# ---------------------------------------------------------
p_branch <- DimPlot(
  combined_alltp_noadult,
  reduction = "umap",
  group.by = "branch",
  cols = branch_pal,
  #label = TRUE,
  repel = TRUE
) + ggtitle("UMAP by Branch")

p_branch <- DimPlot(
  combined_alltp,
  reduction = "umap",
  group.by = "subareas",
  #cols = branch_pal,
  #label = TRUE,
  repel = TRUE
) + ggtitle("UMAP by Branch")

p_branch

```



```{r}
DimPlot(combined_alltp, group.by = "branch", label = TRUE)
```




```{r}
DimPlot(combined_alltp, group.by = c("cell_type_vague"))
FeaturePlot(combined_alltp, features = c( "Meis2","Irx3","Lhx9", 'Pou3f2'),  max.cutoff = 2)

FeaturePlot(combined_alltp, features = c( "Robo3","Lmx1a", "Lhx2", "Meis1"), max.cutoff = 2)
FeaturePlot(combined_alltp, features = c( "Reln", "Pax6", 'Zic1'), max.cutoff = 4)
FeaturePlot(combined_alltp, features = c( "Nr2f2"), max.cutoff = 4)
FeaturePlot(combined_alltp, features = c( "Crabp2"), max.cutoff = 4)
FeaturePlot(combined_alltp, features = c( "Nfib"), max.cutoff = 4)
FeaturePlot(combined_alltp, features = c( "Nfia"), max.cutoff = 4)

```

```{r}
combined_alltp <- FindClusters(combined_alltp, resolution = 2)

```

```{r}
DimPlot(combined_alltp, label =TRUE)
DimPlot(combined_alltp, group.by = "TimePoint", label =TRUE)
DimPlot(combined_alltp, group.by = "cell_type", label =TRUE)
FeaturePlot(combined_alltp, features = c("Nfia"),max.cutoff = 2)
FeaturePlot(combined_alltp, features = c("Nfix"),max.cutoff = 2)
```




```{r}
combined_alltp <- FindClusters(combined_alltp, resolution = 2)

combined_alltp_med <- subset(combined_alltp, idents = c(2,6,19)) # Lmx1a+ branch
```

```{r}
combined_alltp_med <- ScaleData(combined_alltp_med, vars.to.regress = "TimePoint")
```


```{r}
combined_alltp_med <- RunPCA(combined_alltp_med)
combined_alltp_med <- FindNeighbors(combined_alltp_med, dims = 1:30)
#combined_alltp_med <- FindClusters(combined_alltp_med, resolution = 1)
combined_alltp_med <- RunUMAP(combined_alltp_med, dims = 1:30)

```


```{r}
combined_alltp_med <- FindClusters(combined_alltp_med, resolution = 1)

FeaturePlot(combined_alltp_med, features ="Robo3")
FeaturePlot(combined_alltp_med, features ="Irx3")
FeaturePlot(combined_alltp_med, features ="Lhx9")
FeaturePlot(combined_alltp_med, features ="Reln")

DimPlot(combined_alltp_med, group.by ="TimePoint")

DimPlot(combined_alltp_med, label = TRUE, size = 1)
```
```{r}

#--- IRX3 subset ---#
# Extract the cell identities and clusters
combined_alltp_med_irx3 <- subset(combined_alltp_med, idents = c(3,4,2,5,6,7))
combined_alltp_med_reln <- subset(combined_alltp_med, idents = c(0,1,10))

#--- Create a new metadata column in your full object ---#
combined_alltp$med_2p <- "Other"

#--- Get cell names from your two subset objects ---#
irx3_cells <- Cells(combined_alltp_med_irx3)
reln_cells <- Cells(combined_alltp_med_reln)
early_cells <- Cells(subset(combined_alltp, idents = c(8,9,14,0)))
late_cells <- Cells(subset(combined_alltp, idents = c(1,4)))

#--- Label cells according to which subset they came from ---#
combined_alltp$med_2p[irx3_cells] <- "Early Medial"
combined_alltp$med_2p[reln_cells] <- "Late Medial"
combined_alltp$med_2p[early_cells] <- "Early Medial"
combined_alltp$med_2p[late_cells] <- "Late Medial"
#--- Convert to factor for cleaner plotting ---#
#combined_alltp$med_2p <- factor(combined_alltp$med_2p, levels = c("ealy", "RELN", "Other"))

#--- Check how many cells got each label ---#
table(combined_alltp$med_2p)

#--- Visualize on your full integrated UMAP ---#
DimPlot(combined_alltp, group.by = "med_2p") 

DimPlot(combined_alltp, label=TRUE) 


```

```{r}
combined_alltp_e13 = subset(combined_alltp, TimePoint == "E14.5")

# 1) Set identities to your medial stage annotation
Idents(combined_alltp_e13) <- "med_2p"

# Check levels to confirm names
levels(combined_alltp_e13)
# should contain "early_medial" and "late_medial"

# 2) Find DE markers: early vs late medial
library(dplyr)
library(tibble)

# Up in Early Medial
early_up <- early_vs_late_medial %>%
  rownames_to_column("gene") %>%
  arrange(desc(avg_log2FC)) %>%      # positive = higher in Early
  slice_head(n = 15) %>%
  pull(gene)

# Up in Late Medial
late_up <- early_vs_late_medial %>%
  rownames_to_column("gene") %>%
  arrange(avg_log2FC) %>%            # negative = higher in Late
  slice_head(n = 15) %>%
  pull(gene)

top_genes <- c(early_up, late_up)

DoHeatmap(combined_alltp_e13, features = top_genes) + NoLegend()



```
```{r}
library(dplyr)
library(clusterProfiler)
library(org.Mm.eg.db)  # use org.Hs.eg.db for human

# Map symbols -> Entrez IDs
entrez_ids <- bitr(
  top_genes,
  fromType = "SYMBOL",
  toType   = "ENTREZID",
  OrgDb    = org.Mm.eg.db
)

gene_entrez <- unique(entrez_ids$ENTREZID)
ego_bp <- enrichGO(
  gene          = gene_entrez,
  OrgDb         = org.Mm.eg.db,
  keyType       = "ENTREZID",
  ont           = "BP",
  pAdjustMethod = "BH",
  pvalueCutoff  = 0.05,
  qvalueCutoff  = 0.05,
  readable      = TRUE       # convert back to gene symbols
)

head(as.data.frame(ego_bp))
barplot(ego_bp, showCategory = 20)
dotplot(ego_bp, showCategory = 20)

```
```{r}
library(clusterProfiler)
library(org.Mm.eg.db)
library(GO.db)
library(AnnotationDbi)


# get all descendants of "developmental process" (GO:0032502)
dev_root <- "GO:0032502"
dev_ids  <- unique(c(dev_root, unlist(AnnotationDbi::as.list(GOBPOFFSPRING[dev_root]))))

# keep only developmental-process terms
ego_dev <- ego_bp[ego_bp@result$ID %in% dev_ids]

# (optional) reduce redundancy among the kept terms
#ego_dev <- simplify(ego_dev, cutoff=0.6, by="p.adjust", select_fun=min)

head(as.data.frame(ego_bp))
#barplot(ego_dev, showCategory = 20)
dotplot(ego_dev, showCategory = 20)
```

```{r}
combined_alltp <- FindClusters(combined_alltp, resolution =2)
DimPlot(combined_alltp, group.by = "SCT_snn_res.2", label = TRUE)
```


```{r}
library(dplyr)
library(Seurat)
library(ggplot2)

# ---------------------------------------------------------
# 1. Recode SCT clusters into branch categories
# ---------------------------------------------------------
combined_alltp$branch_corr <- recode(
  combined_alltp$SCT_snn_res.2,
  
  "0"  = "Int/Lat Prog", 
  "1"  = "Med",
  "2"  = "Med", 
  "3"  = "IntA",
  "4"  = "RL", 
  "5"  = "IntA/Lat",
  "6"  = "Med", 
  "7"  = "IntA/Lat",
  "8"  = "RL", 
  "9"  = "Int/Lat Prog",
  "10" = "IntP", 
  "11" = "IntA",
  "12" = "Lat",
  "13" = "IntP", 
  "14" = "Med",
  "15" = "Med",
  "16" = "IntP", 
  "17" = "Med",
  "18" = "IntP",
  "19"  = "Med",
  "20" = "IntA/Lat", 
  "21" = "Med",
  "22" = "Lat",
  "23" = "IntP", 
  "24" = "IntP",
  "25" = "IntP",
  "26" = "IntP"
)

# ---------------------------------------------------------
# 2. Branch color palette
# ---------------------------------------------------------
branch_pal <- c(
  "Int/Lat Prog" = "#ff9913",
  "Med"          = "blue",
  "IntA/Lat"     = "red",
  "RL"           = "lightblue",
  "IntP"         = "#007a00",
  "Med_gly"      = "#17becf",
  "early"        = "brown",
  "late"          = "blue",
  "RL"
)

# ---------------------------------------------------------
# 3. Convert med_2p to character so labels NEVER become numbers
# ---------------------------------------------------------
combined_alltp$med_2p <- as.character(combined_alltp$med_2p)

# ---------------------------------------------------------
# 4. Replace "Other" with branch — keep as character!
# ---------------------------------------------------------
combined_alltp$med_2p_branch <- ifelse(
  combined_alltp$med_2p == "Other",
  as.character(combined_alltp$branch),
  combined_alltp$med_2p
)

# explicitly ensure it's character
combined_alltp$med_2p_branch <- as.character(combined_alltp$med_2p_branch)

# ---------------------------------------------------------
# 5. Build palette for all med_2p_branch groups
# ---------------------------------------------------------
groups <- unique(combined_alltp$med_2p_branch)

# Keep branch colors for matching groups
pal_med2p_branch <- branch_pal[names(branch_pal) %in% groups]

# Add colors for extra med_2p categories not in branch palette
missing_groups <- groups[!groups %in% names(branch_pal)]

if (length(missing_groups) > 0) {
  set.seed(1)
  extra_cols <- setNames(
    grDevices::colors()[sample(1:600, length(missing_groups))],
    missing_groups
  )
  pal_med2p_branch <- c(pal_med2p_branch, extra_cols)
}

# ---------------------------------------------------------
# 6. Plot UMAP without losing labels
# ---------------------------------------------------------
DimPlot(
  combined_alltp,
  group.by = "branch_corr",
  cols = branch_pal,
  label = TRUE,
  repel = TRUE
)


DimPlot(
  combined_alltp,
  group.by = "SCT_snn_res.2",
  cols = pal_med2p_branch,
  label = TRUE,
  repel = TRUE
)
```

```{r}
library(dplyr)
library(Seurat)
library(ggplot2)

# ---------------------------------------------------------
# 0. Convert SCT cluster IDs to character (CRITICAL FIX)
# ---------------------------------------------------------
#combined_alltp$SCT_snn_res.1.2 <- as.character(combined_alltp$SCT_snn_res.1.2)

# ---------------------------------------------------------
# 1. Recode SCT clusters into branch categories
# ---------------------------------------------------------
combined_alltp$branch <- recode(
  combined_alltp$SCT_snn_res.2,
  
  "0"  = "Int/Lat Prog", 
  "1"  = "Med",
  "2"  = "Med", 
  "3"  = "IntA",
  "4"  = "RL", 
  "5"  = "IntA/Lat",
  "6"  = "Med", 
  "7"  = "IntA/Lat",
  "8"  = "RL", 
  "9"  = "Int/Lat Prog",
  "10" = "IntP", 
  "11" = "IntA",
  "12" = "Lat",
  "13" = "IntP", 
  "14" = "Early Medial",
  "15" = "Med",
  "16" = "IntP", 
  "17" = "Med",
  "18" = "IntP",
  "19"  = "Med",
  "20" = "IntA/Lat", 
  "21" = "Med",
  "22" = "Lat",
  "23" = "IntP", 
  "24" = "IntP",
  "25" = "IntP",
  "26" = "IntP"
)

# ---------------------------------------------------------
# 2. Color palette
# ---------------------------------------------------------
branch_pal <- c(
  "Int/Lat Prog" = "#ff9913",
  #"Med"          = "blue",
  "IntA/Lat"     = "red",
  "IntA"     = "#D19",
  "Lat"     = "#950606",
  "RL"           = "lightblue",
  #"IntP/IntA"  
  "IntP"         = "#228B22",
  "Med_gly"      = "#17becf",
  "Early Medial"        = "#8a6740",
  "Late Medial"         = "blue"
)
# ---------------------------------------------------------
# 3. Ensure med_2p is character
# ---------------------------------------------------------
combined_alltp$med_2p <- as.character(combined_alltp$med_2p)
combined_alltp$branch <- as.character(combined_alltp$branch)

# ---------------------------------------------------------
# 4. "Other" gets branch label
# ---------------------------------------------------------
combined_alltp$med_2p_branch <- ifelse(
  combined_alltp$med_2p == "Other",
  combined_alltp$branch,
  combined_alltp$med_2p
)

# ---------------------------------------------------------
# 4b. Priority override: RL and Int/Lat Prog always win
# ---------------------------------------------------------
combined_alltp$med_2p_branch <- ifelse(
  combined_alltp$branch %in% c("RL", "Int/Lat Prog"),
  combined_alltp$branch,
  combined_alltp$med_2p_branch
)


# ---------------------------------------------------------
# 5. Palette for all groups
# ---------------------------------------------------------
groups <- unique(combined_alltp$med_2p_branch)
pal_med2p_branch <- branch_pal[names(branch_pal) %in% groups]

missing_groups <- groups[!groups %in% names(branch_pal)]
if (length(missing_groups) > 0) {
  set.seed(1)
  extra_cols <- setNames(
    grDevices::colors()[sample(1:600, length(missing_groups))],
    missing_groups
  )
  pal_med2p_branch <- c(pal_med2p_branch, extra_cols)
}
```


```{r}
# ---------------------------------------------------------
# 6. Plot UMAP
# ---------------------------------------------------------
DimPlot(
  combined_alltp,
  group.by = "med_2p_branch",
  #cols = pal_med2p_branch,
  label = TRUE,
  repel = TRUE)

```

################################################ SUPERVISED PSEUDOTIME ###################################################


```{r}

run_monocle_trajectory <- function(
  seu_object,
  cluster_column,
  traj_clusters,
  root_cluster = "RL_late",
  genes_of_interest,
  gene_colors,
  timepoint_colors = NULL,
  y_limits = NULL,
  exclude_timepoint = "adult",
  scale_genes = FALSE
) {
  
  library(Seurat)
  library(monocle3)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(RColorBrewer)
  
  ## 1️⃣ Set identities
  Idents(seu_object) <- cluster_column
  
  ## 2️⃣ Subset clusters
  seu_traj <- subset(seu_object, med_2p_branch_final %in% traj_clusters)
  
  if (!is.null(exclude_timepoint)) {
    seu_traj <- subset(seu_traj, TimePoint != exclude_timepoint)
  }
  
  ## 3️⃣ Convert to cds
  cds <- as.cell_data_set(seu_traj)
  colData(cds)$cluster <- Idents(seu_traj)
  reducedDims(cds)$UMAP <- Embeddings(seu_traj, "umap")
  
  ## 4️⃣ Force single partition
  partition <- factor(rep(1, ncol(cds)))
  names(partition) <- colnames(cds)
  cds@clusters$UMAP$partitions <- partition
  cds@clusters$UMAP$clusters   <- colData(cds)$cluster
  
  ## 5️⃣ Learn trajectory and set root
  cds <- learn_graph(cds)
  root_cells <- colnames(cds)[colData(cds)$cluster == root_cluster]
  cds <- order_cells(cds, reduction_method = "UMAP", root_cells = root_cells)
  
  ## 6️⃣ Extract pseudotime and metadata
  pt <- pseudotime(cds)
  meta_df <- as.data.frame(colData(cds))
  meta_df$pseudotime <- pt
  # Extract pseudotime from branch cds

  # Get branch cell names
  branch_cells <- colnames(cds)
  
  # Add pseudotime column to full Seurat object
  seu_object$branch_pseudotime <- NA
  
  seu_object$branch_pseudotime[
    colnames(seu_object) %in% branch_cells
  ] <- pt
  if (!"TimePoint" %in% colnames(meta_df)) stop("cds must have a TimePoint column in colData")
  meta_df$TimePoint <- factor(meta_df$TimePoint, levels = sort(unique(meta_df$TimePoint)))
  
  ## 7️⃣ Timepoint colors
  if (is.null(timepoint_colors)) {
    timepoint_colors <- RColorBrewer::brewer.pal(n = length(levels(meta_df$TimePoint)), "Blues")
    names(timepoint_colors) <- levels(meta_df$TimePoint)
  }
  
  ## 8️⃣ Gene expression data
  rowData(cds)$gene_short_name <- rownames(cds)
  expr_mat <- exprs(cds)[genes_of_interest, ]
  df_genes <- as.data.frame(t(expr_mat))
  df_genes$pseudotime <- pt
  
  df_long <- df_genes %>%
    pivot_longer(cols = all_of(genes_of_interest),
                 names_to = "gene",
                 values_to = "expression")
  
  if (scale_genes) {
    df_long <- df_long %>%
      group_by(gene) %>%
      mutate(expression = scale(expression))
  }
  
  # Smooth values for ribbon shading
  df_smooth <- df_long %>%
    group_by(gene) %>%
    arrange(pseudotime) %>%
    summarise(
      smooth_expr = stats::predict(stats::loess(expression ~ pseudotime, data = cur_data())),
      pseudotime = pseudotime
    )
  
  ## 9️⃣ Build combined pseudotime plot
  p <- ggplot() +
    # Cells projected below x-axis by TimePoint
    geom_jitter(data = meta_df,
                aes(x = pseudotime, y = -0.5, color = TimePoint),
                height = 0, size = 1.5, alpha = 0.8) +
    # Shaded gene curves
    geom_ribbon(data = df_smooth,
                aes(x = pseudotime, ymin = 0, ymax = smooth_expr, fill = gene),
                alpha = 0.3) +
    geom_line(data = df_smooth,
              aes(x = pseudotime, y = smooth_expr, color = gene),
              linewidth = 1.2) +
    scale_fill_manual(values = gene_colors) +
    scale_color_manual(values = c(timepoint_colors, gene_colors)) +
    theme_classic() +
    labs(title = "Cells and gene expression along pseudotime",
         x = "Pseudotime",
         y = "Expression",
         color = "Legend", fill = "Genes")
  
  if (!is.null(y_limits)) {
    p <- p + ylim(y_limits)
  }
  
  print(p)
  
  ## 10️⃣ Optional: Plot UMAP trajectory
  p1 <- plot_cells(cds, reduction_method = "UMAP",
                   color_cells_by = "cluster",
                   label_cell_groups = TRUE,
                   show_trajectory_graph = TRUE)
  p2 <- plot_cells(cds, reduction_method = "UMAP",
                   color_cells_by = "pseudotime",
                   show_trajectory_graph = TRUE)
  
  print(p1)
  print(p2)
  
  return(list(cds = cds, seu_object = seu_object))
}
```


```{r}
# SET 1 #
genes_of_interest1 = c("Lhx9", "Pax6")
gene_colors1 = c("Lhx9" = "red", "Pax6" = "green")

# SET 1 #
genes_of_interest2 = c("Olig2", "Irx3", "Lmx1a")
gene_colors2 = c("Olig2" = "#7fc97f", "Irx3" = "#E1ad01", "Lmx1a" = 'brown')

# SET 3 #
genes_of_interest3 = c("Prox1", "Zfpm2")
gene_colors3 = c("Prox1" = "pink", "Zfpm2" = "red")


# SET 3 #
genes_of_interest4 = c("Dcc", "Unc5c")
gene_colors4 = c("Dcc" = "pink", "Unc5c" = "red")

# SET 3 #
genes_of_interest5 = c("Robo3", "Robo2")
gene_colors5 = c("Robo3" = "darkgreen", "Robo2" = "green")

# SET 3 #
genes_of_interest6 = c("Plxna2", "Plxnd1")
gene_colors6 = c("Plxna2" = "darkblue", "Plxnd1" = "blue")


timepoint_colors <- c(
  "adult" = "red",
  "E11.5" = "#E1ad01",
  "E12.5" = "#7fc97f",
  "E13.5" = "#139fb6",
  "E14.5" = "#009be6",
  "E16.5"   = "#98aacb",
  "E17" = "#f37dce"

)
```


```{r}
DefaultAssay(combined_alltp) <- "SCT"
data  <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Lat", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest1,
  gene_colors = gene_colors1,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 25),  # extra space below for cells
  scale_genes = FALSE
)
```
```{r}
DefaultAssay(combined_alltp) <- "SCT"
data1 <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntA", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest1,
  gene_colors = gene_colors1,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 25),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
data2 <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntP"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest1,
  gene_colors = gene_colors1,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 25),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
data3 <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Early Medial"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest1,
  gene_colors = gene_colors1,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 25),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
data4 <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_late",  "Late Medial"),
  root_cluster = "RL_late",
  genes_of_interest = genes_of_interest1,
  gene_colors = gene_colors1,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 25),  # extra space below for cells
  scale_genes = FALSE
)
```

```{r}

traj_lat <- data$seu_object
library(ggplot2)

FeaturePlot(
  traj_lat,
  features = "branch_pseudotime",
  reduction = "umap"
) +
  scale_color_viridis_c(
    option = "magma",
    na.value = "grey85"
  ) +
  theme_classic()


traj_inta <- data1$seu_object
library(ggplot2)

FeaturePlot(
  traj_inta,
  features = "branch_pseudotime",
  reduction = "umap"
) +
  scale_color_viridis_c(
    option = "magma",
    na.value = "grey85"
  ) +
  theme_classic()

traj_intp <- data2$seu_object
library(ggplot2)

FeaturePlot(
  traj_intp,
  features = "branch_pseudotime",
  reduction = "umap"
) +
  scale_color_viridis_c(
    option = "magma",
    na.value = "grey85"
  ) +
  theme_classic()

traj_early <- data3$seu_object
library(ggplot2)

FeaturePlot(
  traj_early,
  features = "branch_pseudotime",
  reduction = "umap"
) +
  scale_color_viridis_c(
    option = "magma",
    na.value = "grey85"
  ) +
  theme_classic()


traj_late <- data4$seu_object
library(ggplot2)

FeaturePlot(
  traj_late,
  features = "branch_pseudotime",
  reduction = "umap"
) +
  scale_color_viridis_c(
    option = "magma",
    na.value = "grey85"
  ) +
  theme_classic()
```

```{r}
DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Lat", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest2,
  gene_colors = gene_colors2,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntA", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest2,
  gene_colors = gene_colors2,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntP"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest2,
  gene_colors = gene_colors2,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Early Medial"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest2,
  gene_colors = gene_colors2,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_late",  "Late Medial"),
  root_cluster = "RL_late",
  genes_of_interest = genes_of_interest2,
  gene_colors = gene_colors2,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)
```


```{r}
DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Lat", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest3,
  gene_colors = gene_colors3,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 3),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntA", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest3,
  gene_colors = gene_colors3,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 3),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntP"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest3,
  gene_colors = gene_colors3,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 3),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Early Medial"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest3,
  gene_colors = gene_colors3,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 3),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_late",  "Late Medial"),
  root_cluster = "RL_late",
  genes_of_interest = genes_of_interest3,
  gene_colors = gene_colors3,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 3),  # extra space below for cells
  scale_genes = FALSE
)
```


```{r}


DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntA", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest4,
  gene_colors = gene_colors4,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)


DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Early Medial"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest4,
  gene_colors = gene_colors4,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_late",  "Late Medial"),
  root_cluster = "RL_late",
  genes_of_interest = genes_of_interest4,
  gene_colors = gene_colors4,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)
```





```{r}


DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntA", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest6,
  gene_colors = gene_colors6,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)


DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Early Medial"),
  root_cluster = "RL_early",
  genes_of_interest = genes_of_interest6,
  gene_colors = gene_colors6,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)

DefaultAssay(combined_alltp) <- "SCT"
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_late",  "Late Medial"),
  root_cluster = "RL_late",
  genes_of_interest = genes_of_interest6,
  gene_colors = gene_colors6,
  timepoint_colors = timepoint_colors,
  y_limits = c(-2, 10),  # extra space below for cells
  scale_genes = FALSE
)
```

```{r}
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntA", "IntA/Lat"),
  root_cluster = "RL_early",
  genes_of_interest = c("Prox1", "Zfpm2"),
  gene_colors = c("Prox1" = "pink",
                  "Zfpm2" = "red"),
  scale_genes = FALSE
)
```
```{r}
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "IntP"),
  root_cluster = "RL_early",
  genes_of_interest = c("Prox1", "Zfpm2"),
  gene_colors = c("Prox1" = "pink",
                  "Zfpm2" = "red"),
  scale_genes = FALSE
)
```
```{r}
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_early", "Int/Lat Prog", "Early Medial"),
  root_cluster = "RL_early",
  genes_of_interest = c("Lmx1a", "Irx3", "Olig2"),
  gene_colors = c("Lmx1a" = "brown",
                  "Irx3" = "orange",
                  "Olig2" = "green"),
  scale_genes = FALSE
)
```

```{r}
cds_result <- run_monocle_trajectory(
  seu_object = combined_alltp,
  cluster_column = "med_2p_branch_final",
  traj_clusters = c("RL_late", "Late Medial"),
  root_cluster = "RL_late",
  genes_of_interest = c("Lmx1a", "Irx3", "Olig2"),
  gene_colors = c("Lmx1a" = "brown",
                  "Irx3" = "orange",
                  "Olig2" = "green"),
  scale_genes = FALSE
)
```




################################################ HEATMAP EARLY VS LATE ###################################################





```{r}
# 2) Pull a *single* counts matrix from RNA
# LayerData is the v5-safe way; choose one counts layer (usually counts.1)
# Subset the ORIGINAL object directly - this is the v5-correct way
combined_alltp_EARLY <- subset(combined_alltp, TimePoint %in% c("E12.5", "E13.5"))
med_cells <- WhichCells(
  combined_alltp_EARLY,
  expression = med_2p_branch %in% c("Early Medial", "Late Medial")
)

# ONE LINE - subset keeps ALL layers intact, perfectly aligned
combined_alltp_med_clean <- subset(combined_alltp_EARLY, cells = med_cells)

# Set up for analysis
DefaultAssay(combined_alltp_med_clean) <- "RNA"
Idents(combined_alltp_med_clean) <- combined_alltp_med_clean$med_2p_branch



# DE analysis
de_early_medial <- FindAllMarkers(combined_alltp_med_clean,  min.pct = 0.25, logfc.threshold = 0.5, group.by = "med_2p_branch")


```
```{r}
# Write de_early_medial to a tab-separated text file
write.table(
  de_early_medial, 
  file = "de_early_medial_results.txt", 
  sep = "\t",
  quote = FALSE, 
  row.names = FALSE
)

```


```{r}

# Add cluster info to top50 and order genes by cluster + abs(log2FC)
top50 <- de_early_medial %>%
  group_by(cluster) %>%
  slice_max(order_by = avg_log2FC, n = 50, with_ties = FALSE) %>%
  ungroup() %>%
  # Order: Early cluster genes first (highest abs FC), then Late cluster genes
  arrange(cluster, desc(abs(avg_log2FC))) %>%
  # Add cluster label as prefix for grouping in heatmap
  mutate(gene_label = paste0(cluster, "_", gene))

# Scale with the labeled genes (but plot original names)
combined_alltp_med_clean <- ScaleData(
  combined_alltp_med_clean, 
  features = top50$gene  # Use original gene names for scaling
)

# Plot - genes now grouped by cluster origin (Early_*, Late_*)
DoHeatmap(
  combined_alltp_med_clean,
  features = top50$gene,  # Original gene names
  group.by = "med_2p_branch",
  label = TRUE  # Shows gene names
)


```


```{r}
library(clusterProfiler)
library(org.Mm.eg.db)   # mouse annotation
library(enrichplot)
library(dplyr)

# pick significant genes by adjusted p-value
sig_genes <- top50$gene

gene_entrez <- bitr(
  sig_genes,
  fromType = "SYMBOL",
  toType   = "ENTREZID",
  OrgDb    = org.Mm.eg.db
) %>% pull(ENTREZID)

# optional: remove NA and duplicates
gene_entrez <- unique(gene_entrez[!is.na(gene_entrez)])

ego_bp <- enrichGO(
  gene          = gene_entrez,
  OrgDb         = org.Mm.eg.db,
  keyType       = "ENTREZID",
  ont           = "BP",        # biological process; can also use "MF" or "CC"
  pAdjustMethod = "BH",
  pvalueCutoff  = 0.05,
  qvalueCutoff  = 0.2,
  readable      = TRUE         # convert Entrez IDs back to symbols
)
```


```{r}
library(ggplot2)
library(dplyr)
library(forcats)

neuronal_df <- as.data.frame(ego_bp)[
  grep("neuron|neurogenesis|nervous|brain|axon|dendrite|synapse", 
       ego_bp$Description, ignore.case = TRUE), 
] %>%
  arrange(desc(GeneRatio)) %>%   # optional, for the table itself
  head(20) %>%
  mutate(
    neg_log_p = -log10(p.adjust),
    GeneRatio_num = as.numeric(sub("/.*", "", GeneRatio)) / 
                    as.numeric(sub(".*\\/", "", GeneRatio)),
    Description = reorder(Description, GeneRatio_num)   # ⬅️ THIS
  )

# Manual publication-ready dotplot
ggplot(neuronal_df, aes(x = GeneRatio_num, y = Description, 
                       size = Count, color = neg_log_p)) +
  geom_point(alpha = 0.8) +
  scale_color_viridis_c(name = "-log10(p.adj)", direction = 1) +
  scale_size_continuous(range = c(3, 8), name = "Gene Count") +
  labs(title = "Neuronal Development GO Terms", 
       x = "Gene Ratio", y = "") +
  theme_minimal(base_size = 12) +
  theme(
    axis.text.y = element_text(size = 10),
    plot.title = element_text(hjust = 0.5, face = "bold")
  )


```

